#!/usr/bin/env bash
# =============================================================================
# battlemage-setup install script
#
# This script sets up the top-layer tooling (llama-swap service, opencode,
# and pi coding agent). It assumes the lower-level stack (Intel oneAPI,
# llama.cpp SYCL build, Intel compute-runtime) is already in place.
# See PREREQUISITES below.
#
# NOTE: This script discovers models from their .params files (generated by
# 03-discover-models.sh) and builds llama-swap.yaml dynamically.
#
# Tested target: Ubuntu 24.04, Intel Battlemage GPU
# =============================================================================

# --- PREREQUISITES (must be satisfied manually before running this script) ---
#
# HARDWARE
#   [ ] Intel Battlemage GPU (e.g., Arc B570, B580, Pro B70)
#   [ ] Host machine
#   [ ] NVMe storage with enough space for GGUF model files
#
# OS & KERNEL
#   [ ] Ubuntu 24.04 LTS (or compatible distro)
#   [ ] Kernel with xe driver support for Battlemage (>=6.8; >=6.17 preferred)
#       Verify: uname -r   and   lsmod | grep xe
#
# INTEL GPU STACK
#   [ ] Intel compute-runtime v26.09+ installed from GitHub releases
#       (the APT repo version is too old for Battlemage/Xe2)
#       https://github.com/intel/compute-runtime/releases
#       Install the .deb packages: intel-opencl-icd, libze-intel-gpu1,
#       intel-ocloc, intel-igc-core-2, intel-igc-opencl-2
#   [ ] Intel oneAPI Base Toolkit installed at /opt/intel/oneapi/
#       https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit.html
#       Verify: source /opt/intel/oneapi/setvars.sh && sycl-ls
#       (should list the Battlemage GPU as a Level Zero device)
#
# LLAMA.CPP (SYCL BUILD)
#   [ ] llama.cpp cloned and built with SYCL support
#       Build in a oneAPI-initialized shell:
#         source /opt/intel/oneapi/setvars.sh
#         cmake -S . -B build -G Ninja \
#           -DGGML_SYCL=ON \
#           -DCMAKE_C_COMPILER=icx \
#           -DCMAKE_CXX_COMPILER=icpx
#         cmake --build build -j$(nproc)
#   [ ] llama-server binary accessible on $PATH or at a known path
#       (e.g. ~/llama.cpp/build/bin/llama-server)
#
# MODEL DISCOVERY
#   [ ] GGUFs placed under ~/.lmstudio/models/<owner>/<repo>/
#   [ ] Run 03-discover-models.sh first to generate .params files
#
# =============================================================================

set -euo pipefail

# ── Configuration — edit these before running ────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# llama-swap
LLAMA_SWAP_VERSION="latest"   # or pin to a specific tag, e.g. "v0.0.32"
LLAMA_SWAP_PORT=8080          # the single OpenAI-compatible endpoint
LLAMA_SWAP_CONFIG="$HOME/.config/llama-swap/llama-swap.yaml"

# llama.cpp binary path (adjust to where you built it)
LLAMA_SERVER_BIN="$HOME/llama.cpp/build/bin/llama-server"

# Models directory (must match MODELS_DIR in 03-discover-models.sh)
MODELS_DIR="$HOME/.lmstudio/models"

# llama-swap YAML defaults (applied to every generated model/group entry)
LLAMA_HEALTH_CHECK_TIMEOUT=180
LLAMA_LOG_LEVEL="info"
LLAMA_MODEL_TTL=0
LLAMA_GROUP_SWAP=true
LLAMA_GROUP_EXCLUSIVE=false

# Linger user (the user whose session hosts the systemd unit)
LINGER_USER="${USER}"

# ─────────────────────────────────────────────────────────────────────────────

log()  { echo "==> $*"; }
warn() { echo "WARN: $*" >&2; }
die()  { echo "ERROR: $*" >&2; exit 1; }

# ── 0. Sanity checks ─────────────────────────────────────────────────────────

log "Checking prerequisites..."

[[ -f /opt/intel/oneapi/setvars.sh ]] \
  || die "Intel oneAPI not found at /opt/intel/oneapi/setvars.sh. Install it first."

# Source oneAPI so sycl-ls and icpx are on PATH for the rest of this script
# shellcheck disable=SC1091
#source /opt/intel/oneapi/setvars.sh --force 2>/dev/null || true

#command -v sycl-ls >/dev/null 2>&1 \
#  || die "sycl-ls not found after sourcing oneAPI. Check your oneAPI install."

#sycl-ls | grep -qi "level_zero" \
#  || warn "No Level Zero device found via sycl-ls. The Battlemage GPU may not be detected yet."

[[ -f "$LLAMA_SERVER_BIN" ]] \
  || die "llama-server not found at $LLAMA_SERVER_BIN. Build llama.cpp with SYCL first."

[[ -d "$MODELS_DIR" ]] \
  || die "Models directory not found at $MODELS_DIR. Run 03-discover-models.sh first."

# ── 1. Install llama-swap binary ─────────────────────────────────────────────

log "Installing llama-swap..."
mkdir -p "$HOME/.local/bin"

# Determine target version: if "latest", fetch from GitHub.
if [[ "$LLAMA_SWAP_VERSION" == "latest" ]]; then
  info "Fetching latest llama-swap version..."
  LLAMA_SWAP_LATEST=$(curl -fsSL \
    "https://api.github.com/repos/mostlygeek/llama-swap/releases/latest" \
    | grep '"tag_name"' | head -1 | cut -d '"' -f 4 || true)
  # Strip leading 'v' if present, e.g. "v234" -> "234"
  LLAMA_SWAP_LATEST="${LLAMA_SWAP_LATEST#v}"
  info "Latest version: $LLAMA_SWAP_LATEST"
else
  LLAMA_SWAP_LATEST="$LLAMA_SWAP_VERSION"
fi

SKIP_SWAP=0
if command -v llama-swap >/dev/null 2>&1; then
  INSTALLED_SWAP=$(llama-swap version 2>/dev/null | grep -oP 'version:\s*\K[0-9]+' || true)
  if [[ -n "$INSTALLED_SWAP" ]]; then
    info "llama-swap already installed: $INSTALLED_SWAP"
    if [[ "$INSTALLED_SWAP" -ge "$LLAMA_SWAP_LATEST" ]] 2>/dev/null; then
      info "Version is current — skipping download."
      SKIP_SWAP=1
    else
      info "Installed version ($INSTALLED_SWAP) is older than target ($LLAMA_SWAP_LATEST) — upgrading."
    fi
  else
    warn "Could not parse llama-swap version — will re-install."
  fi
fi

if [[ "$SKIP_SWAP" -eq 0 ]]; then
  # Fetch latest Linux amd64 release archive
  LLAMA_SWAP_URL=$(curl -fsSL \
    "https://api.github.com/repos/mostlygeek/llama-swap/releases/latest" \
    | grep "browser_download_url" \
    | grep "linux_amd64.tar.gz" \
    | head -1 \
    | cut -d '"' -f 4)

  if [[ -z "$LLAMA_SWAP_URL" ]]; then
    die "Could not determine llama-swap download URL. Download manually from https://github.com/mostlygeek/llama-swap/releases"
  fi

  log "Downloading llama-swap from $LLAMA_SWAP_URL..."

  SWAP_TMPDIR=$(mktemp -d)
  trap 'rm -rf "$SWAP_TMPDIR"' EXIT

  curl -fsSL -o "$SWAP_TMPDIR/llama-swap.tar.gz" "$LLAMA_SWAP_URL"

  tar -xzf "$SWAP_TMPDIR/llama-swap.tar.gz" -C "$SWAP_TMPDIR"

  LLAMA_SWAP_BIN=$(find "$SWAP_TMPDIR" -type f -name "llama-swap" | head -1)

  if [[ -z "$LLAMA_SWAP_BIN" ]]; then
    die "Could not find llama-swap binary inside downloaded archive."
  fi

  install -m 755 "$LLAMA_SWAP_BIN" "$HOME/.local/bin/llama-swap"

  log "Installed llama-swap:"
  "$HOME/.local/bin/llama-swap" version || true
fi

# Ensure ~/.local/bin is on PATH
if [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
  warn "~/.local/bin is not in PATH. Add it to your shell rc file:"
  warn '  echo '\''export PATH="$HOME/.local/bin:$PATH"'\'' >> ~/.bashrc'
fi

# ── 2. Install the bundled llm-swap helper ──────────────────────────────────

log "Installing llm-swap helper..."
mkdir -p "$HOME/.local/bin"

if [[ -f "$SCRIPT_DIR/llm-swap" ]]; then
  cp "$SCRIPT_DIR/llm-swap" "$HOME/.local/bin/llm-swap"
  chmod +x "$HOME/.local/bin/llm-swap"
  log "Installed llm-swap helper."
else
  warn "llm-swap helper not found in script directory."
fi

# ── 3. Discover models and generate llama-swap.yaml ──────────────────────────

log "Discovering GGUF models and generating config..."
mkdir -p "$(dirname "$LLAMA_SWAP_CONFIG")"

# Collect all discovered model metadata by scanning for .params files.
# Each discovered model contributes:
#   - gguf path
#   - alias (from --alias in params)
#   - port  (from --port in params)
#   - extra flags (everything except -m, --host, --port, --alias, --verbose, and log redirection)
declare -a DIS_GGUF=()
declare -a DIS_ALIAS=()
declare -a DIS_PORT=()
declare -a DIS_EXTRA=()
declare -a DIS_VERBOSE=()

params_found=0

while IFS= read -r -d '' gguf; do
  params_file="${gguf}.llama.cpp.params"

  if [[ ! -f "$params_file" ]]; then
    warn "No params file for $gguf — skipping."
    continue
  fi

  alias_val=""
  port_val=""
  extra_flags=""
  verbose_flag=""

  while IFS= read -r line; do
    # Trim whitespace
    line="${line#"${line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"
    # Skip blanks and comments
    [[ -z "$line" ]] && continue
    [[ "$line" == \#* ]] && continue

    # Extract --alias value
    if [[ "$line" == --alias* ]]; then
      alias_val="${line#--alias }"
      alias_val="${alias_val#--alias}"
      alias_val="${alias_val#"${alias_val%%[![:space:]]*}"}"
      continue
    fi

    # Extract --port value
    if [[ "$line" == --port* ]]; then
      port_val="${line#--port }"
      port_val="${port_val#--port}"
      port_val="${port_val#"${port_val%%[![:space:]]*}"}"
      continue
    fi

    # Extract --verbose flag (no value)
    if [[ "$line" == "--verbose" ]]; then
      verbose_flag="--verbose"
      continue
    fi

    # Skip --host (we hardcode 127.0.0.1 in the cmd)
    if [[ "$line" == --host* ]]; then
      continue
    fi

    # Everything else is an extra flag to pass through
    extra_flags+="      $line
"
  done < "$params_file"

  if [[ -z "$alias_val" ]]; then
    warn "Params file $params_file has no --alias — skipping."
    continue
  fi

  if [[ -z "$port_val" ]]; then
    warn "Params file $params_file has no --port — skipping."
    continue
  fi

  DIS_GGUF+=("$gguf")
  DIS_ALIAS+=("$alias_val")
  DIS_PORT+=("$port_val")
  DIS_EXTRA+=("$extra_flags")
  DIS_VERBOSE+=("$verbose_flag")

  params_found=$((params_found + 1))
done < <(find "$MODELS_DIR" -type f -iname '*.gguf' -print0 | sort -z)

if [[ $params_found -eq 0 ]]; then
  die "No GGUF + .params pairs found under $MODELS_DIR. Run 03-discover-models.sh first."
fi

log "Found $params_found model(s)."

# ── Collect unique ports for groups ──────────────────────────────────────────

declare -A PORT_SEEN=()
declare -a UNIQUE_PORTS=()

for port_val in "${DIS_PORT[@]}"; do
  if [[ -z "${PORT_SEEN[$port_val]+_}" ]]; then
    PORT_SEEN[$port_val]=1
    UNIQUE_PORTS+=("$port_val")
  fi
done

# ── Write YAML ───────────────────────────────────────────────────────────────

if [[ -f "$LLAMA_SWAP_CONFIG" ]]; then
  log "llama-swap.yaml already exists at $LLAMA_SWAP_CONFIG — overwriting."
fi

{
  echo "healthCheckTimeout: $LLAMA_HEALTH_CHECK_TIMEOUT"
  echo "logLevel: $LLAMA_LOG_LEVEL"
  echo ""
  echo "models:"

  for i in "${!DIS_ALIAS[@]}"; do
    alias_val="${DIS_ALIAS[$i]}"
    gguf="${DIS_GGUF[$i]}"
    port_val="${DIS_PORT[$i]}"
    extra_flags="${DIS_EXTRA[$i]}"
    verbose="${DIS_VERBOSE[$i]}"

    echo "  ${alias_val}:"
    echo "    proxy: http://127.0.0.1:${port_val}"
    echo "    ttl: $LLAMA_MODEL_TTL"
    echo "    cmd: >"
    echo "      bash -c \"source /opt/intel/oneapi/setvars.sh; exec ${LLAMA_SERVER_BIN}"
    echo "      -m ${gguf}"

    # Emit extra flags (preserving one-per-line formatting for readability)
    if [[ -n "$extra_flags" ]]; then
      printf '%s' "$extra_flags"
    fi

    echo "      --host 127.0.0.1 --port ${port_val}"
    echo "      --alias ${alias_val}"
    if [[ -n "$verbose" ]]; then
      echo "      --verbose"
    fi
    echo "      2>> ${HOME}/.llama-server-${alias_val}.log\""
    echo ""
  done

  echo "groups:"

  for port_val in "${UNIQUE_PORTS[@]}"; do
    echo "  port${port_val}:"
    echo "    persistent: true"
    echo "    swap: $LLAMA_GROUP_SWAP"
    echo "    exclusive: $LLAMA_GROUP_EXCLUSIVE"
    echo "    members:"

    for i in "${!DIS_PORT[@]}"; do
      if [[ "${DIS_PORT[$i]}" == "$port_val" ]]; then
        echo "      - \"${DIS_ALIAS[$i]}\""
      fi
    done
    echo ""
  done
} > "$LLAMA_SWAP_CONFIG"

log "Written $LLAMA_SWAP_CONFIG ($params_found models, ${#UNIQUE_PORTS[@]} groups)."

# ── 4. Create systemd user unit for llama-swap ───────────────────────────────

log "Creating systemd user unit for llama-swap..."
UNIT_DIR="$HOME/.config/systemd/user"
mkdir -p "$UNIT_DIR"

cat > "$UNIT_DIR/llama-swap.service" <<UNIT
[Unit]
Description=llama-swap LLM proxy (Intel Battlemage GPU)
After=network.target

[Service]
Type=simple
# Source oneAPI environment so llama-server can find SYCL/Level-Zero
Environment="PATH=/opt/intel/oneapi/compiler/latest/bin:%h/.local/bin:/usr/local/bin:/usr/bin:/bin"
ExecStart=/bin/bash -c 'source /opt/intel/oneapi/setvars.sh --force; exec %h/.local/bin/llama-swap --config %h/.config/llama-swap/llama-swap.yaml --listen 0.0.0.0:${LLAMA_SWAP_PORT}'
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
UNIT

systemctl --user daemon-reload
systemctl --user enable llama-swap.service
log "Systemd unit installed and enabled."

# ── 5. Enable linger so the service survives logout ───────────────────────────

log "Enabling linger for $LINGER_USER (requires sudo)..."
sudo loginctl enable-linger "$LINGER_USER" \
  && log "Linger enabled." \
  || warn "Could not enable linger — run manually: sudo loginctl enable-linger $LINGER_USER"

# ── 6. Write opencode config ──────────────────────────────────────────────────

log "Writing opencode config..."
OPENCODE_CONFIG_DIR="$HOME/.config/opencode"
mkdir -p "$OPENCODE_CONFIG_DIR"

# Build model entries from discovered models.
default_model="${DIS_ALIAS[0]}"

{
  echo '{'
  echo '  "$schema": "https://opencode.ai/config.json",'
  echo ''
  echo '  "provider": {'
  echo '    "local": {'
  echo '      "npm": "@ai-sdk/openai-compatible",'
  echo '      "name": "Local (llama-swap)",'
  echo '      "options": {'
  echo "        \"baseURL\": \"http://127.0.0.1:${LLAMA_SWAP_PORT}/v1\","
  echo '        "apiKey": "local"'
  echo '      },'
  echo '      "models": {'

  for i in "${!DIS_ALIAS[@]}"; do
    alias_val="${DIS_ALIAS[$i]}"
    # Derive a human-readable name by capitalising each segment of the alias.
    readable=$(echo "$alias_val" | sed -e 's/-/ /g' -e 's/\b\(.\)/\u\1/g')
    comma=","
    if [[ $i -eq $((${#DIS_ALIAS[@]} - 1)) ]]; then
      comma=""
    fi
    echo "        \"${alias_val}\": {"
    echo "          \"name\": \"${readable}\""
    echo "        }${comma}"
  done

  echo '      }'
  echo '    }'
  echo '  },'
  echo ''
  echo "  \"model\": \"local/${default_model}\""
  echo '}'
} > "$OPENCODE_CONFIG_DIR/opencode.json"

log "Generated opencode.json with $params_found model(s)."

# Install opencode if not already present
if ! command -v opencode >/dev/null 2>&1; then
  log "Installing opencode..."
  if command -v npm >/dev/null 2>&1; then
    npm install -g opencode-ai
  else
    warn "npm not found. Install Node.js, then run: npm install -g opencode"
  fi
else
  log "opencode already installed: $(command -v opencode)"
fi

# ── 7. Write pi coding agent config ──────────────────────────────────────────

log "Writing pi config..."
PI_CONFIG_DIR="$HOME/.pi/agent"
mkdir -p "$PI_CONFIG_DIR"

{
  echo '{'
  echo '  "providers": {'
  echo '    "local": {'
  echo "      \"baseUrl\": \"http://127.0.0.1:${LLAMA_SWAP_PORT}/v1\","
  echo '      "api": "openai-completions",'
  echo '      "apiKey": "local",'
  echo '      "compat": {'
  echo '        "supportsDeveloperRole": false,'
  echo '        "supportsReasoningEffort": false,'
  echo '        "supportsUsageInStreaming": false'
  echo '      },'
  echo '      "models": ['

  for i in "${!DIS_ALIAS[@]}"; do
    alias_val="${DIS_ALIAS[$i]}"
    readable=$(echo "$alias_val" | sed -e 's/-/ /g' -e 's/\b\(.\)/\u\1/g')
    comma=","
    if [[ $i -eq $((${#DIS_ALIAS[@]} - 1)) ]]; then
      comma=""
    fi
    echo "        { \"id\": \"${alias_val}\", \"name\": \"${readable}\" }${comma}"
  done

  echo '      ]'
  echo '    }'
  echo '  }'
  echo '}'
} > "$PI_CONFIG_DIR/models.json"

log "Generated pi models.json with $params_found model(s)."

# Install pi if not already present
if ! command -v pi >/dev/null 2>&1; then
  log "Installing pi coding agent..."
  if command -v npm >/dev/null 2>&1; then
    npm install -g @mariozechner/pi-coding-agent
  else
    warn "npm not found. Install Node.js, then run: npm install -g @mariozechner/pi-coding-agent"
  fi
else
  log "pi already installed: $(command -v pi)"
fi

# ── 8. Start the service ─────────────────────────────────────────────────────

log "Starting llama-swap service..."
systemctl --user start llama-swap.service
sleep 3

if systemctl --user is-active --quiet llama-swap.service; then
  log "llama-swap is running."
else
  warn "llama-swap failed to start. Check: journalctl --user -u llama-swap -n 50"
fi

# ── Done ──────────────────────────────────────────────────────────────────────

# Build list of aliases for summary.
model_list=""
for alias_val in "${DIS_ALIAS[@]}"; do
  model_list+="    llm-swap ${alias_val}"$'\n'
done

cat <<SUMMARY

=============================================================================
  Installation complete
=============================================================================

Service management:
  systemctl --user status|start|stop|restart llama-swap.service
  journalctl --user -u llama-swap -f          # live logs

Model preloading:
${model_list}  llm-swap list | status | unload

opencode (interactive TUI):
  opencode                                    # default model (${default_model})
  opencode -m local/<model>               # switch model

pi coding agent:
  pi --provider local --model <model>
  pi config                                   # TUI for extensions

API endpoint:
  http://127.0.0.1:${LLAMA_SWAP_PORT}/v1/chat/completions
  (OpenAI-compatible; set model to any discovered alias)

Models discovered : $params_found
Groups (ports)    : ${#UNIQUE_PORTS[@]}

Review and adjust these files before relying on this setup:
  $LLAMA_SWAP_CONFIG
  $HOME/.config/opencode/opencode.json
  $HOME/.pi/agent/models.json
=============================================================================
SUMMARY
